#Requires -Version 5.1
<#
.SYNOPSIS
    Brave Omega - Silent Policy Deployment Script (Intune Win32)

.DESCRIPTION
    Deploys a Brave Omega policy level to HKLM:\SOFTWARE\Policies\BraveSoftware\Brave
    by importing the matching enterprise registry artifact (enterprise\<Level>.reg)
    and verifying the result against the generated policy catalog (levels.json).

    Designed to run as SYSTEM from an Intune Win32 app install command. It is silent,
    writes a log, and does NOT restart the browser. Policies take effect on the next
    Brave launch.

.PARAMETER Level
    Policy level to deploy. Valid values follow the catalog
    (BraveOnly, Essential, Balanced, Advanced, Strict). Default: Balanced.

.PARAMETER PayloadDir
    Directory that contains the enterprise\<Level>.reg artifact and levels.json.
    Default: the directory of this script.

.PARAMETER RegistryPath
    Registry base path to target. Default: HKLM:\SOFTWARE\Policies\BraveSoftware\Brave

.PARAMETER LogDirectory
    Directory for the deployment log. Default: %ProgramData%\BraveOmega\Logs
    (fallback: %TEMP%\BraveOmega).

.PARAMETER NoLog
    Disables log file output.

.PARAMETER WhatIf
    Show what would be done without importing or writing anything.

.INPUTS
    None. You cannot pipe objects to this script.

.OUTPUTS
    System.Int32 - Exit code. 0 = deployed, 1 = failed.

.EXAMPLE
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\scripts\deploy-brave-omega.ps1 -Level Strict

    Deploys the Strict level from the local enterprise folder.

.EXAMPLE
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File deploy-brave-omega.ps1 -Level Balanced

    Intune Win32 install command line for the Balanced level.

.NOTES
    - Re-running at a lower level does NOT remove policies introduced by a higher level;
      registry deletes are out of scope for the Win32 deployment path.
    - The catalog contract (levels.json + enterprise artifacts) is generated by
      scripts\Export-PolicyCatalog.ps1 and cross-checked by Tests\DeploymentScripts.Tests.ps1.
#>

param(
    [ValidateSet("BraveOnly", "Essential", "Balanced", "Advanced", "Strict")]
    [string]$Level = "Balanced",

    [string]$PayloadDir = "",

    [string]$RegistryPath = "HKLM:\SOFTWARE\Policies\BraveSoftware\Brave",

    [string]$LogDirectory = "",

    [switch]$NoLog,

    [switch]$WhatIf
)

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

function Get-OmegaLevelOrder {
    return @("BraveOnly", "Essential", "Balanced", "Advanced", "Strict")
}

function Test-OmegaAdministrator {
    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    if ($null -eq $identity) { return $false }
    $principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-OmegaPayloadBase {
    param([string]$PayloadDir)
    if ($PayloadDir) { return $PayloadDir }
    if ($PSScriptRoot) { return $PSScriptRoot }
    return (Get-Location).Path
}

function Resolve-OmegaRegPayload {
    param([string]$PayloadDir, [string]$Level)

    $base = Get-OmegaPayloadBase -PayloadDir $PayloadDir

    $candidates = @(
        (Join-Path $base "enterprise\$Level.reg")
        (Join-Path $base "$Level.reg")
    )

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }
    }

    throw "No registry artifact found for level '$Level'. Expected one of: $($candidates -join ', '). Regenerate with scripts\Export-PolicyCatalog.ps1."
}

function Resolve-OmegaLevelsJson {
    param([string]$PayloadDir)

    $base = Get-OmegaPayloadBase -PayloadDir $PayloadDir

    $candidates = @(
        (Join-Path $base "enterprise\levels.json")
        (Join-Path $base "levels.json")
    )

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }
    }

    throw "No levels.json catalog found. Expected one of: $($candidates -join ', '). Regenerate with scripts\Export-PolicyCatalog.ps1."
}

function Get-OmegaLevelNamesFromCatalog {
    param([string]$JsonPath, [string]$Level)

    $json = Get-Content -LiteralPath $JsonPath -Raw | ConvertFrom-Json

    $levelNode = $json.levels.$Level
    if ($null -eq $levelNode) {
        throw "Level '$Level' is not present in the catalog."
    }

    $names = @()
    foreach ($policy in @($levelNode.policies)) {
        if ($null -ne $policy) { $names += [string]$policy.name }
    }

    return @($names | Sort-Object)
}

function Get-OmegaPolicyRegistryView {
    param([string]$RegistryPath)

    $exists = Test-Path -LiteralPath $RegistryPath
    $valueNames = @()
    $subKeyNames = @()

    if ($exists) {
        $item = Get-Item -LiteralPath $RegistryPath -ErrorAction SilentlyContinue
        if ($null -ne $item -and $null -ne $item.Property) {
            $valueNames = @($item.Property)
        }
        $children = @(Get-ChildItem -LiteralPath $RegistryPath -ErrorAction SilentlyContinue)
        foreach ($child in $children) {
            if ($null -ne $child.PSChildName) {
                $subKeyNames += [string]$child.PSChildName
            }
        }
    }

    return [pscustomobject]@{
        Exists      = $exists
        ValueNames  = $valueNames
        SubKeyNames = $subKeyNames
    }
}

function Test-OmegaLevelPresent {
    param([string]$RegistryPath, [string[]]$ExpectedNames)

    $view = Get-OmegaPolicyRegistryView -RegistryPath $RegistryPath
    if (-not $view.Exists) { return $false }

    $available = New-Object System.Collections.Generic.HashSet[string] ([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($name in @($view.ValueNames)) { [void]$available.Add([string]$name) }
    foreach ($name in @($view.SubKeyNames)) { [void]$available.Add([string]$name) }

    foreach ($expected in @($ExpectedNames)) {
        if (-not $available.Contains($expected)) { return $false }
    }

    return $true
}

function Write-OmegaLog {
    param([switch]$NoLog, [string]$LogDirectory, [string]$Message)

    if ($NoLog -or -not $LogDirectory) { return }

    try {
        if (-not (Test-Path -LiteralPath $LogDirectory)) {
            New-Item -ItemType Directory -Path $LogDirectory -Force | Out-Null
        }
        $line = "{0} [deploy-brave-omega] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message
        Add-Content -LiteralPath (Join-Path $LogDirectory "deploy-brave-omega.log") -Value $line -Encoding ASCII
    } catch {
        Write-Warning "Failed to write log: $($_.Exception.Message)"
    }
}

function Invoke-OmegaRegImport {
    param([string]$RegFilePath)

    if (-not (Test-Path -LiteralPath $RegFilePath)) {
        Write-Warning "Registry artifact not found: $RegFilePath"
        return $false
    }

    & reg.exe import $RegFilePath 2>&1 | Out-Null
    return ($LASTEXITCODE -eq 0)
}

function Get-OmegaDefaultLogDirectory {
    if ($env:ProgramData) {
        return (Join-Path $env:ProgramData "BraveOmega\Logs")
    }
    return (Join-Path $env:TEMP "BraveOmega")
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if ($MyInvocation.InvocationName -ne ".") {

    $logDir = $LogDirectory
    if (-not $logDir) { $logDir = Get-OmegaDefaultLogDirectory }

    try {
        if ($WhatIf) {
            $regFile = Resolve-OmegaRegPayload -PayloadDir $PayloadDir -Level $Level
            $jsonFile = Resolve-OmegaLevelsJson -PayloadDir $PayloadDir
            $expectedNames = Get-OmegaLevelNamesFromCatalog -JsonPath $jsonFile -Level $Level
            Write-Host "WHATIF: Would deploy level '$Level' ($(@($expectedNames).Count) cumulative policies)."
            Write-Host "WHATIF: Import $regFile and verify against $RegistryPath."
            Write-Host "WhatIf operation completed."
            exit 0
        }

        if (-not (Test-OmegaAdministrator)) {
            throw "Elevation required. Deploy-brave-omega.ps1 must run as SYSTEM or an elevated administrator."
        }

        Write-OmegaLog -NoLog:$NoLog -LogDirectory $logDir -Message "Starting deployment of level '$Level'."

        $regFile = Resolve-OmegaRegPayload -PayloadDir $PayloadDir -Level $Level
        $jsonFile = Resolve-OmegaLevelsJson -PayloadDir $PayloadDir

        $expectedNames = Get-OmegaLevelNamesFromCatalog -JsonPath $jsonFile -Level $Level
        $totalPolicies = @($expectedNames).Count

        Write-OmegaLog -NoLog:$NoLog -LogDirectory $logDir -Message "Level '$Level' expects $totalPolicies cumulative policies."
        Write-OmegaLog -NoLog:$NoLog -LogDirectory $logDir -Message "Importing registry artifact: $regFile"

        $imported = $false
        try {
            $imported = Invoke-OmegaRegImport -RegFilePath $regFile
        } catch {
            Write-OmegaLog -NoLog:$NoLog -LogDirectory $logDir -Message "reg.exe import failed: $($_.Exception.Message)"
            throw
        }

        if (-not $imported) {
            throw "reg.exe import returned a non-zero exit code for $regFile."
        }

        $present = Test-OmegaLevelPresent -RegistryPath $RegistryPath -ExpectedNames $expectedNames
        if (-not $present) {
            throw "Verification failed: not all $totalPolicies expected policies are present under $RegistryPath."
        }

        Write-OmegaLog -NoLog:$NoLog -LogDirectory $logDir -Message "Deployment of level '$Level' verified: all $totalPolicies policies present."
        Write-Host "Deployed Brave Omega level '$Level' ($totalPolicies policies)."
        exit 0
    } catch {
        $message = $_.Exception.Message
        Write-OmegaLog -NoLog:$NoLog -LogDirectory $logDir -Message "ERROR: $message"
        Write-Warning "deploy-brave-omega.ps1 failed: $message"
        exit 1
    }
}